---
title: "M12 Exercises"
output: html_document
date: '2022-07-07'
---
```{r}
library(tidyverse)


scores <- 
  tibble(
    name = c("mike", "carol", "greg", "marcia", "peter", "jan", "bobby", "cindy", "alice"),
    school = c("south", "south", "south", "south", "north", "north", "north", "south", "south"),
    teacher = c("johnson", "johnson", "johnson", "johnson",  "smith", "smith", "smith", "perry", "perry"),
    sex = c("male", "female", "male", "female", "male", "female", "male", "female", "female"),
    math_score = c(4, 3, 2, 4, 3, 4, 5, 4, 5),
    reading_score = c(1, 5, 2, 4, 5, 4, 1, 5, 4)
)
```

Exercise 12.3

```{r}
scores
```

Exercise 12.4

```{r}
scores %>%
  slice(1:3)
```

```{r}
myvar <- scores %>%
  slice(1:3)
myvar
```
Exercise 12.5

```{r}
scores %>%
  arrange(desc(math_score))
```

Exercise 12.6

```{r}
scores %>%
  arrange(name)
```

Exercise 12.7

```{r}
scores %>%
  group_by(sex) %>%
  summarize(reading_score_av=mean(reading_score), math_score_av=mean(math_score))
```
Females have better reading scores

Exercise 12.8

```{r}
scores %>%
  arrange(school, teacher, sex, math_score, reading_score)
```

Exercise 12.9

```{r}
scores %>%
  select(name, math_score, reading_score)
```

Exercise 12.10

```{r}
scores %>%
  select(-sex)
```

Exercise 12.11

```{r}
scores %>%
  select(-math_score, -reading_score)
```

Exercise 12.12

```{r}
scores %>%
  select(sex, everything())
```

Exercise 12.13

```{r}
scores %>%
  filter(math_score >= 4)
```

Exercise 12.14

```{r}
scores %>%
  filter(sex == 'male' & school == 'south')
```

Exercise 12.15

```{r}
scores %>%
  filter(math_score >= 4 & reading_score >= 3)
```

Exercise 12.16

```{r}
scores %>%
  filter(reading_score == 2 | reading_score == 3 | reading_score == 4)
```

Exercise 12.17

```{r}
scores %>%
  filter(substr(name, 1, 1) == "m")
```

Exercise 12.18

```{r}
scores %>%
  group_by(teacher) %>%
  filter(math_score == 5)
```

Exercise 12.19

```{r}
scores %>%
  group_by(sex) %>%
  filter(mean(math_score) == 4)
```

Exercises 12.22

```{r}
scores %>%
  mutate(math_reading_avg = (math_score + reading_score)/2)
```

Exercise 12.23

```{r}
scores %>%
  mutate(high_math_achiever = (math_score >= 4))
```

Exercise 12.27

```{r}
scores %>%
  group_by(teacher) %>%
  mutate(reading_score_centered_by_teacher = (reading_score - mean(reading_score)))
```

Exercise 12.28

```{r}
scores %>%
  group_by(teacher) %>%
  mutate(number_of_students_in_class = n())
```

Exercise 12.29

```{r}
scores %>%
  summarize(mean_math = mean(math_score))
```

Exercise 12.31

```{r}
scores %>%
  summarize(math_median = median(math_score), reading_median = median(reading_score))
```

Exercise 12.32

```{r}
scores %>%
  group_by(school) %>%
  summarize(minimum_math_score = min(math_score))
```

Exercise 12.36

```{r}
scores %>%
  select(name, math_score) %>%
  mutate(math_score_ec = math_score + 5) %>%
  arrange(math_score_ec)
```

Exercise 12.38

```{r}
scores %>%
  filter(teacher != "smith") %>%
  group_by(sex) %>%
  summarize(mean_math_score = mean(math_score))
```

